image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'
vscode:
  extensions:
    - avli.clojure@0.13.1:5Nh2zxjCTtylndwZRsKxng==